#define MAX_TAM_IDENT 20
#define PROGRAM "program"
#define BEGIN "begin"
#define END "end"
#define CONST "const"
#define VIRGULA "virgula"
#define PROCEDURE "procedure"
#define PARENTESES_ESQUERDO "parenteses esquerdo"
#define PARENTESES_DIREITO "parenteses direito"
#define PONTO_E_VIRGULA "ponto e virgula"
#define PONTO "ponto"
#define ELSE "else"
#define READ "read"
#define WRITE "write"
#define WHILE "while"
#define DO "do"
#define IF "if"
#define THEN "then"
#define ATRIBUICAO "atribuicao"
#define IGUAL "igual"
#define MAIOR_IGUAL "maior igual"
#define MENOR_IGUAL "menos igual"
#define MAIOR "maior"
#define MENOR "menor"
#define MAIS "mais"
#define MENOS "menos"
#define VEZES "vezes"
#define DIVIDIDO "dividido"
#define COMENTARIO "comentario"
#define DOIS_PONTOS "dois pontos"
#define IDENTIFICADOR "identificador"
#define VAR "var"
#define REAL "real"
#define INTEGER "integer"
#define NUM_INTEIRO "numero inteiro"
#define NUM_REAL "numero real"
#define NUMERO_INT_MAL_FORMADO "numero inteiro mal formado"
#define NUMERO_REAL_MAL_FORMADO "numero real mal formado"
#define CARACTERES_INVALIDOS "caracter invalido na linguaguem"



